### ISSUE TITLE
Relvals are not getting updated with new jira ticket ID

### ISSUE THREAD

**Issue by pkalbhor** [cms-AlCaDB/AlCaVal#34]
We can create new Jira ticket for the AlCaVal ticket. 
It involves:
1. Creating Jira  ticket.
2. After that it should update list of relvals associated with that ticket with ID of Jira ticket. 
Second step is not getting executed.

**Comment by pkalbhor** [comment]
Tested successfully with this ticket:
https://alcaval.web.cern.ch/tickets?prepid=CMSSW_13_0_3__ECAL-00001

Closing the issue.

**Comment by pkalbhor** [comment]
Seems to be a bug. This is the error after `Create Jira Ticket` button is clicked.
```bash
[13-May-23 10:37:09 UTC][fbrivio][ERROR] Traceback (most recent call last):
  File "/usr/src/app/core_lib/api/api_base.py", line 84, in exceptions_to_errors_wrapper
    return func(*args, **kwargs)
  File "/usr/src/app/core_lib/api/api_base.py", line 117, in ensure_role_wrapper_wrapper
    return func(*args, **kwargs)
  File "/usr/src/app/api/jira_api.py", line 31, in put
    jira_ticket = jira_controller.create_ticket(jira_json)
  File "/usr/src/app/api/controller/jira_controller.py", line 35, in create_ticket
    new_issue = connection.create_issue(fields = fields)
  File "/usr/local/lib/python3.9/site-packages/jira/client.py", line 1473, in create_issue
    r = self._session.post(url, data=json.dumps(data))
  File "/usr/local/lib/python3.9/site-packages/jira/resilientsession.py", line 198, in post
    return self.__verb("POST", str(url), data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jira/resilientsession.py", line 189, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jira/resilientsession.py", line 64, in raise_on_error
    raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://its.cern.ch:443/jira/rest/api/2/issue
        text: Component name '' is not valid

        response headers = {'Cache-Control': 'no-cache, no-store, no-transform', 'Content-Security-Policy': 'sandbox', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Sat, 13 May 2023 10:37:09 GMT', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Server': 'nginx', 'Strict-Transport-Security': 'max-age=31536000', 'X-Arequestid': '757x7391999x1', 'X-Asessionid': 'hhdtxn', 'X-Ausername': 'alcauser', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Seraph-Loginreason': 'OK', 'X-Xss-Protection': '1; mode=block', 'Content-Length': '77'}
        response text = {"errorMessages":[],"errors":{"components":"Component name '' is not valid"}}
 (api_base.py:86)
```

@francescobrivio , @teteumac was it the case where you were passing empty component name or extra comma (while creating jira ticket on alcaval)?

**Comment by francescobrivio** [comment]
Hi @pkalbhor I got the error when I was passing an empty component name.
As soon as I added a component the JIRA was created!

**Comment by pkalbhor** [comment]
Thanks @francescobrivio I am implementing solution for this case where we pass empty component name.

**Comment by teteumac** [comment]
@saumyaphor4252 and @consuegs  This issue has already been resolved and it has to do with the last commit I just made to fix the Jira token as well. We can close this ticket as well if necessary.

**Comment by consuegs** [comment]
@teteumac, can you include here for documentation the PR with the commit that solves the issue opened here? Then we proceed with the closing of this issue

**Comment by consuegs** [comment]
As already tagged above, given my mention on the PR, the corresponding PR addressing the issue open here is:
[[PROD] correction of Jira's PUT to POST method #56](https://github.com/cms-AlCaDB/AlCaVal/pull/56)
